services:

  users-app:
    container_name: users-app
    build:
      context: ./users
    depends_on:
      - users-db
    env_file:
      - ./.env.users

  users-migrate:
    build:
      context: ./users
    depends_on:
      - users-db
    volumes:
      - ./users/alembic.ini:/app/alembic.ini:ro
    env_file:
      - ./.env.users
    command: /app/.venv/bin/alembic -c /app/alembic.ini upgrade head

  users-db:
    container_name: users-db
    image: postgres:17.6-bookworm
    volumes:
      - pkb-users-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.users

  notes-app:
    container_name: notes-app
    build:
      context: ./notes
    depends_on:
      - notes-db
    env_file:
      - ./.env.notes

  notes-migrate:
    build:
      context: ./notes
    depends_on:
      - notes-db
    volumes:
      - ./notes/alembic.ini:/app/alembic.ini:ro
    env_file:
      - ./.env.notes
    command: /app/.venv/bin/alembic -c /app/alembic.ini upgrade head

  notes-db:
    container_name: notes-db
    image: postgres:15
    volumes:
      - pkb-notes-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.notes

  nginx:
    container_name: nginx
    image: nginx:1.29-bookworm
    depends_on:
      - users-app
      - notes-app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pkb-users-db-data:
  pkb-notes-db-data:
