---
rbac:
  create: false

serviceAccount:
  create: false

testFramework:
  enabled: false

service:
  enabled: true
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - pkb.grafana.local

persistence:
  enabled: true

admin:
 existingSecret: "grafana"
 userKey: user
 passwordKey: password

datasources:
  datasources.yaml:
    # Configuration file version
    apiVersion: 1
    datasources:
      # <string, required> Sets the name you use to refer to
      # the data source in panels and queries.
    - name: Loki

      # <string, required> Sets the data source type.
      type: loki

      # <string, required> Sets the access mode, either
      # proxy or direct (Server or Browser in the UI).
      # Some data sources are incompatible with any setting
      # but proxy (Server).
      access: proxy

      # <string> Sets the data source's URL, including the port.
      url: http://loki-gateway.default.svc.cluster.local:80

      # <bool> Enables basic authorization.
      basicAuth: false

      # <bool> Toggles whether the data source is pre-selected
      # for new panels. You can set only one default
      # data source per organization.
      isDefault: false

      # <int> Sets the version. Used to compare versions when
      # updating. Ignored when creating a new data source.
      version: 1

      # <bool> Allows users to edit data sources from the Grafana UI.
      editable: false
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.default.svc.cluster.local:80
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
