#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# https://minikube.sigs.k8s.io/docs/handbook/pushing/#1-pushing-directly-to-the-in-cluster-docker-daemon-docker-env
eval $(minikube docker-env)

docker build -t pkb-users ./users
docker build -t pkb-notes ./notes

find ./k8s -name "*.yaml" | grep -v migrate | xargs -I % minikube kubectl -- apply -f %
